# this docker compose file is for development only
services:
  frontend:
    container_name: godoxy-frontend-next
    restart: no
    network_mode: host
    image: godoxy-frontend
    env_file: .env
    environment:
      NEXT_PUBLIC_GODOXY_API_ADDR: ${GODOXY_API_ADDR}
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    labels:
      proxy.aliases: godoxy-dev
      proxy.*: |
        port: 3002
        healthcheck:
          disabled: true
        homepage:
          show: false
